### PR TITLE
fix: Swap only

### PR DESCRIPTION
**Pull request by zly2006**

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
Other than cleaning up some Debug logger's, is this ready ?

**Comment by zly2006** [comment]
hmm, currently the swap only mode can use all slots in your inventory, and if under packet rate limiter, it works very well.

however, the incorrect results are crafted under swap only mode, which mismatches with the description. I still dont know why it is happening.

**Comment by sakura-ryoko** [comment]
If you want to do more research that is fine, I'll wait to merge.  I don't expect that issue to be fixed in particular, I am mostly concerned about having it working better for PaperMC users, with the Packet Buffering.

**Comment by zly2006** [comment]
OK please merge it then. I’ll open another PR if I eventually succeed.

**Pull request merged**
